settings:
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 5002
  host: localhost
schema:
  - name: 3mm4
    path: .
    commands:
      run:
        status: true
    watcher:
      paths:
        - /
      extensions:
        - go
      ignored_paths:
        - .git
        - .realize
        - vendor
